### ISSUE TITLE
Wow damn. The second youtube-dl

### ISSUE THREAD

**Issue by weisk** [tomer8007/widevine-l3-decryptor#25]
Thank you tomer, for freeing this knowledge to the world!!!!

**Comment by Aholicknight** [comment]
Before this was removed, I forked it.
![image](https://user-images.githubusercontent.com/7843719/99006068-7ef64680-2507-11eb-8e07-fc8e29c568e7.png)
Sadly, every fork from this repo was taken down.

**Comment by geeknik** [comment]
Don't worry, archive.org has you covered. Just search for `Widevine`. LOL

**Comment by Liqianyu** [comment]
https://github.com/tomer8007/widevine-l3-decryptor/tree/ed8a97745c69b8cc0fc7f59cec9474b216b49e16

**Comment by Aholicknight** [comment]
The revolution has already started. People are beginning to archive the repo and post it to tons of other sites.

Welcome to the Streisand effect.

**Comment by ValZapod** [comment]
Serious question: when Level 1 will be supported? Or it also need RSA private key like in linux?

**Comment by Aholicknight** [comment]
@ValZapod Level 1 has already been bypassed from the looks of it. The scene has probably found a way to rip L1 movies & TV shows because that is what they are uploading (WEB-DL) and them saying how they did it is probably 0. If they told everyone how they did it, Netflix + WideVine would probably patch how they did it.

**Comment by ValZapod** [comment]
> probably found a way to rip L1 movies

Mmm, no. Everything I saw from AMZN is WebRip and is reencoded by x265 (ffmpeg). So is Netflix.

> probably patch how they did it

You cannot patch hardware keys...

**Comment by yolanda123a** [comment]
i have a link of hb o go latam in mpd 
how can download? nilada dont work and dash proxy dosent work anymore
any suggesion

**Comment by Aholicknight** [comment]
@yolanda123a This is not a support forum to help with you ripping shows. Ask anywhere else but here.

**Comment by yolanda123a** [comment]
> @yolanda123a This is not a support forum to help with you ripping shows. Ask anywhere else but here.

why you not answer?  piece of jerk son of hooker
all peopple use this drm dash together "Widevine L3 decryptor" extension in chrome 88 to get key for decrypt amazon/hbo max/netflix etc etc
I ask where I want to
Because without what the fuck is this forum for?
You have to report this plugin because you use it to hack movies and you don't say anything because you are very afraid that they will discover you and patch the method.
You son of a bitch, your mother is a whore, a prostitute swallows semen with AIDS

**Comment by HawkLiking** [comment]
@tomer8007 need to clean up around here

**Comment by Aholicknight** [comment]
> Because without what the fuck is this forum for?
@yolanda123a 
This forum is for reporting **ISSUES** not asking for support. Do you know the difference between reporting issues and asking for help? Clearly you don't.

**Comment by Aholicknight** [comment]
@tomer8007 Lock this as well.
