### ISSUE TITLE
extract device id blob and private key from android phone

### ISSUE THREAD

**Issue by abderrahmanesaad** [tomer8007/widevine-l3-decryptor#63]
plz can you help give me idea hint on how to extract device id blob and private key from android phone

**Comment by abderrahmanesaad** [comment]
@HackerBoy0412 i am not making jokes to laugh if you dont want help go away

**Comment by HackerBoy0412** [comment]
The thing is, no one will give you a tutorial public.
So try somewhere else

**Comment by abderrahmanesaad** [comment]
@HackerBoy0412  so give can you guide me to the right place or give it to me you seem to have an idea

**Comment by HackerBoy0412** [comment]
No i havent.
Its will not come public

**Comment by abderrahmanesaad** [comment]
@HackerBoy0412 where somewhere i google it for a lot of days and no info and i know they have a discord to share info but how to get there

**Comment by yolanda123a** [comment]
they have a lot of fear give public , fear the method is down and they can't earn money any more.,
because they earn money a lot of money PIRATE MOVIES AND SERIES
they are criminals who deserve to be reported, all in this github are CRIMINALS
they are criminals who deserve to be reported, all in this github are CRIMINALS
they are criminals who deserve to be reported, all in this github are CRIMINALS
they are criminals who deserve to be reported, all in this github are CRIMINALS
they are criminals who deserve to be reported, all in this github are CRIMINALS
they are criminals who deserve to be reported, all in this github are CRIMINALS
they are criminals who deserve to be reported, all in this github are CRIMINALS
they are criminals who deserve to be reported, all in this github are CRIMINALS
they are criminals who deserve to be reported, all in this github are CRIMINALS
they are criminals who deserve to be reported, all in this github are CRIMINALS

**Comment by yolanda123a** [comment]
https://www.youtube.com/watch?v=v_fRnpIJx9I

For example, here you have a group of discord, dedicated to pirating movies and series with the widevine method. and you have users who claim to have their own bat to download.
what you can do is identify them and find a lawyer, and threaten them, if they do not share the method then proceed with your lawyer and give explanations to a judge for what purpose they want and use the method to download movies and series in a way illegal. threaten them and they pay in justice
